packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "^19"
  react-dom: "^19"
  next: "^15"
  typescript: "^5"
  "@types/node": "^22"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  postcss: "^8"
  tailwindcss: "^4"
  eslint: "^9"
  eslint-config-next: "^15"
  "@eslint/eslintrc": "^3"
  lucide-react: "^0.479.0"
