import { AIAgent } from "./types";

export const agents: AIAgent[] = [
  {
    id: "agent_001",
    name: "AutoGPT",
    description:
      "An autonomous AI agent that attempts to achieve goals by breaking them into sub-tasks and using available tools in an automatic loop.",
    imageUrl:
      "https://raw.githubusercontent.com/Significant-Gravitas/AutoGPT/master/docs/content/imgs/AutoGPT_logo.png",
    category: "Automation",
    tags: ["workflow automation", "productivity", "task automation"],
    developer: "Open Source Community",
    capabilities: ["task automation", "internet browsing", "self-improvement"],
    integrationPlatforms: ["Windows", "MacOS", "Linux"],
    apiEndpoint: "https://github.com/Torantulino/Auto-GPT",
    supportedLanguages: ["English"],
    pricing: { monthly: 0, yearly: 0, freeTier: true },
    licenseType: "open-source",
    popularityScore: 4.7,
    reviewsCount: 3200,
    uptime: 99.9,
    releaseDate: "2023-03-30",
    lastUpdated: "2024-01-01",
    documentationURL: "https://docs.agpt.co/",
    demoURL: "https://www.youtube.com/watch?v=6UjlDG8oK9I",
  },
  {
    id: "agent_002",
    name: "Character.ai",
    description:
      "A conversational AI that allows users to create and interact with AI characters, both fictional and real.",
    imageUrl:
      "https://play-lh.googleusercontent.com/Bi_yZnAHkBQnKyEFeW6VE8tA3QnP-vVuGNHUzHJ_fLVWa_3EoQaGCE5Vc3f_2YPRLw",
    category: "Conversational AI",
    tags: ["chatbot", "entertainment", "interactive AI"],
    developer: "Character Technologies Inc.",
    capabilities: ["text-based conversation", "character customization"],
    integrationPlatforms: ["Web", "Mobile (iOS, Android)"],
    apiEndpoint: "https://beta.character.ai/",
    supportedLanguages: ["English", "Spanish", "French"],
    pricing: { monthly: 10, yearly: 100, freeTier: true },
    licenseType: "subscription",
    popularityScore: 4.5,
    reviewsCount: 4500,
    uptime: 99.8,
    releaseDate: "2022-09-01",
    lastUpdated: "2024-01-01",
    documentationURL: "https://docs.character.ai/",
    demoURL: "https://beta.character.ai/",
  },
  {
    id: "agent_003",
    name: "Claude",
    description:
      "An AI chatbot designed for conversational assistance, offering thoughtful and helpful responses.",
    imageUrl: "https://claude.ai/favicon.svg",
    category: "Conversational AI",
    tags: ["chatbot", "assistant", "text generation"],
    developer: "Anthropic",
    capabilities: ["multi-turn conversation", "context retention"],
    integrationPlatforms: ["Slack", "Web"],
    apiEndpoint: "https://claude.ai",
    supportedLanguages: ["English"],
    pricing: { monthly: 30, yearly: 300, freeTier: false },
    licenseType: "subscription",
    popularityScore: 4.8,
    reviewsCount: 5200,
    uptime: 99.9,
    releaseDate: "2023-01-01",
    lastUpdated: "2024-01-10",
    documentationURL: "https://docs.anthropic.com/",
    demoURL: "https://claude.ai/chat",
  },
  {
    id: "agent_004",
    name: "Bard",
    description:
      "A generative AI chatbot by Google that provides conversational responses based on large-scale language models.",
    imageUrl:
      "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg",
    category: "Conversational AI",
    tags: ["chatbot", "search assistant", "content generation"],
    developer: "Google",
    capabilities: ["text generation", "information retrieval"],
    integrationPlatforms: ["Web", "Android"],
    apiEndpoint: "https://bard.google.com/",
    supportedLanguages: ["English", "German", "Japanese"],
    pricing: { monthly: 0, yearly: 0, freeTier: true },
    licenseType: "free",
    popularityScore: 4.6,
    reviewsCount: 6100,
    uptime: 99.7,
    releaseDate: "2023-02-06",
    lastUpdated: "2024-01-05",
    documentationURL: "https://support.google.com/bard",
    demoURL: "https://bard.google.com/",
  },
  {
    id: "agent_005",
    name: "GitHub Copilot",
    description:
      "An AI-powered coding assistant that helps developers write code faster with intelligent suggestions.",
    imageUrl: "https://avatars.githubusercontent.com/u/18060234",
    category: "Coding Assistant",
    tags: ["code completion", "developer tool", "productivity"],
    developer: "GitHub",
    capabilities: ["code generation", "autocomplete", "error detection"],
    integrationPlatforms: ["VS Code", "JetBrains"],
    apiEndpoint: "https://copilot.github.com/",
    supportedLanguages: ["Python", "JavaScript", "C++", "Java"],
    pricing: { monthly: 10, yearly: 100, freeTier: false },
    licenseType: "subscription",
    popularityScore: 4.9,
    reviewsCount: 8500,
    uptime: 99.95,
    releaseDate: "2021-06-29",
    lastUpdated: "2024-01-15",
    documentationURL: "https://docs.github.com/en/copilot",
    demoURL: "https://copilot.github.com/demo",
  },
  {
    id: "agent_006",
    name: "Midjourney",
    description:
      "An AI-powered image generation tool that creates visuals from text prompts.",
    imageUrl:
      "https://assets-global.website-files.com/6364e65f4f7c10d214af2675/6364e65f4f7c10cf65af26ad_mj-meta-image.png",
    category: "Image Generation",
    tags: ["AI art", "image synthesis", "creative tool"],
    developer: "Midjourney Inc.",
    capabilities: ["text-to-image generation"],
    integrationPlatforms: ["Discord"],
    apiEndpoint: "https://www.midjourney.com",
    supportedLanguages: ["English"],
    pricing: { monthly: 30, yearly: 300, freeTier: false },
    licenseType: "subscription",
    popularityScore: 4.7,
    reviewsCount: 5400,
    uptime: 99.8,
    releaseDate: "2022-07-15",
    lastUpdated: "2024-01-10",
    documentationURL: "https://www.midjourney.com/app/docs",
    demoURL: "https://www.midjourney.com/explore",
  },
  {
    id: "agent_007",
    name: "Penny by Priceline",
    description:
      "An AI assistant developed by Priceline to handle travel-related needs, including booking flights and accommodations.",
    imageUrl: "/placeholder-avatar.png",
    category: "Travel Assistance",
    tags: ["travel booking", "customer support", "automation"],
    developer: "Priceline",
    capabilities: [
      "flight booking",
      "hotel reservations",
      "itinerary management",
    ],
    integrationPlatforms: ["Web", "Mobile (iOS, Android)"],
    apiEndpoint: "https://www.priceline.com/penny",
    supportedLanguages: ["English"],
    pricing: { monthly: 0, yearly: 0, freeTier: true },
    licenseType: "free",
    popularityScore: 4.5,
    reviewsCount: 1200,
    uptime: 99.9,
    releaseDate: "2024-01-20",
    lastUpdated: "2025-01-20",
    documentationURL: "https://www.priceline.com/penny/docs",
    demoURL: "https://www.priceline.com/penny/demo",
  },
  {
    id: "agent_008",
    name: "Bosh by SafetyCulture",
    description:
      "An AI agent employed by SafetyCulture to manage customer queries and schedule meetings.",
    imageUrl: "/placeholder-avatar.png",
    category: "Customer Service",
    tags: ["customer support", "scheduling", "automation"],
    developer: "SafetyCulture",
    capabilities: [
      "query handling",
      "meeting scheduling",
      "customer interaction",
    ],
    integrationPlatforms: ["Web", "Mobile (iOS, Android)"],
    apiEndpoint: "https://www.safetyculture.com/bosh",
    supportedLanguages: ["English"],
    pricing: { monthly: 0, yearly: 0, freeTier: true },
    licenseType: "free",
    popularityScore: 4.3,
    reviewsCount: 900,
    uptime: 99.8,
    releaseDate: "2024-01-20",
    lastUpdated: "2025-01-20",
    documentationURL: "https://www.safetyculture.com/bosh/docs",
    demoURL: "https://www.safetyculture.com/bosh/demo",
  },
  {
    id: "agent_009",
    name: "Aomni",
    description:
      "An AI agent that streamlines the process of researching prospective customers, potentially saving business development representatives hundreds of hours per year.",
    imageUrl: "https://aomni.ai/favicon.ico",
    category: "Business Development",
    tags: ["research", "automation", "sales"],
    developer: "Aomni",
    capabilities: [
      "customer research",
      "data aggregation",
      "insight generation",
    ],
    integrationPlatforms: ["Web"],
    apiEndpoint: "https://www.aomni.ai/api",
    supportedLanguages: ["English"],
    pricing: { monthly: 50, yearly: 500, freeTier: false },
    licenseType: "subscription",
    popularityScore: 4.6,
    reviewsCount: 1100,
    uptime: 99.7,
    releaseDate: "2024-01-20",
    lastUpdated: "2025-01-20",
    documentationURL: "https://www.aomni.ai/docs",
    demoURL: "https://www.aomni.ai/demo",
  },
  {
    id: "agent_010",
    name: "Kore.ai",
    description:
      "An enterprise-grade AI platform for building conversational AI agents and virtual assistants.",
    imageUrl: "https://kore.ai/wp-content/themes/kore/images/favicon.ico",
    category: "Conversational AI",
    tags: ["chatbot", "virtual assistant", "enterprise"],
    developer: "Kore.ai",
    capabilities: [
      "natural language understanding",
      "dialog management",
      "integration with enterprise systems",
    ],
    integrationPlatforms: [
      "Web",
      "Mobile (iOS, Android)",
      "Slack",
      "Microsoft Teams",
    ],
    apiEndpoint: "https://developer.kore.ai/docs/bots/api-guide/",
    supportedLanguages: ["English", "Spanish", "French", "German"],
    pricing: { monthly: 100, yearly: 1000, freeTier: true },
    licenseType: "subscription",
    popularityScore: 4.7,
    reviewsCount: 1500,
    uptime: 99.9,
    releaseDate: "2024-01-20",
    lastUpdated: "2025-01-20",
    documentationURL: "https://developer.kore.ai/docs/",
    demoURL: "https://www.kore.ai/platform/demo/",
  },
  {
    id: "agent_011",
    name: "Jasper",
    description:
      "An AI content creation platform specializing in marketing copy, blog posts, and social media content with built-in SEO optimization.",
    imageUrl: "https://www.jasper.ai/images/favicon.svg",
    category: "Content Creation",
    tags: ["marketing", "copywriting", "content generation"],
    developer: "Jasper.ai",
    capabilities: [
      "blog writing",
      "social media posts",
      "marketing copy",
      "SEO optimization",
    ],
    integrationPlatforms: ["Web", "Chrome Extension"],
    apiEndpoint: "https://www.jasper.ai",
    supportedLanguages: [
      "English",
      "Spanish",
      "French",
      "German",
      "Portuguese",
      "Italian",
    ],
    pricing: { monthly: 49, yearly: 468, freeTier: false },
    licenseType: "subscription",
    popularityScore: 4.6,
    reviewsCount: 3000,
    uptime: 99.8,
    releaseDate: "2021-01-15",
    lastUpdated: "2024-02-15",
    documentationURL: "https://help.jasper.ai",
    demoURL: "https://www.jasper.ai/demo",
  },
  {
    id: "agent_012",
    name: "Synthesia",
    description:
      "An AI video generation platform that creates professional videos using AI avatars and voice synthesis.",
    imageUrl:
      "https://assets-global.website-files.com/61dc0796f359b6145bc06ea6/61dc0796f359b66dfbc06edb_favicon.png",
    category: "Video Generation",
    tags: ["video creation", "AI avatars", "text-to-speech"],
    developer: "Synthesia Ltd",
    capabilities: [
      "AI avatar generation",
      "voice synthesis",
      "video creation",
      "script translation",
    ],
    integrationPlatforms: ["Web"],
    apiEndpoint: "https://www.synthesia.io",
    supportedLanguages: ["65+ languages"],
    pricing: { monthly: 99, yearly: 999, freeTier: false },
    licenseType: "subscription",
    popularityScore: 4.5,
    reviewsCount: 1800,
    uptime: 99.7,
    releaseDate: "2017-06-01",
    lastUpdated: "2024-02-01",
    documentationURL: "https://docs.synthesia.io",
    demoURL: "https://www.synthesia.io/try",
  },
  {
    id: "agent_013",
    name: "Hyperwrite",
    description:
      "An AI writing assistant that helps with academic writing, research papers, and professional documents with advanced grammar and style suggestions.",
    imageUrl: "https://assets.hyperwrite.ai/logo192.png",
    category: "Writing Assistant",
    tags: ["academic writing", "research", "grammar checking"],
    developer: "Hyperwrite AI",
    capabilities: [
      "academic writing",
      "citation assistance",
      "style improvement",
      "research help",
    ],
    integrationPlatforms: ["Web", "Google Docs", "Microsoft Word"],
    apiEndpoint: "https://www.hyperwrite.ai",
    supportedLanguages: ["English"],
    pricing: { monthly: 15, yearly: 144, freeTier: true },
    licenseType: "subscription",
    popularityScore: 4.3,
    reviewsCount: 850,
    uptime: 99.6,
    releaseDate: "2022-03-15",
    lastUpdated: "2024-01-30",
    documentationURL: "https://help.hyperwrite.ai",
    demoURL: "https://www.hyperwrite.ai/try",
  },
  {
    id: "agent_014",
    name: "Runway",
    description:
      "A creative suite powered by AI that enables video editing, motion graphics, and visual effects generation.",
    imageUrl:
      "https://assets-global.website-files.com/629a2c4f8652c0f2759b73e1/62a0aeae4d60a705b5c51b1c_favicon.png",
    category: "Creative Tools",
    tags: ["video editing", "motion graphics", "visual effects"],
    developer: "Runway AI, Inc.",
    capabilities: [
      "video generation",
      "image editing",
      "motion tracking",
      "background removal",
    ],
    integrationPlatforms: ["Web", "macOS"],
    apiEndpoint: "https://runway.com",
    supportedLanguages: ["English"],
    pricing: { monthly: 35, yearly: 336, freeTier: true },
    licenseType: "subscription",
    popularityScore: 4.6,
    reviewsCount: 2100,
    uptime: 99.7,
    releaseDate: "2018-09-01",
    lastUpdated: "2024-02-20",
    documentationURL: "https://docs.runway.com",
    demoURL: "https://runway.com/demo",
  },
  {
    id: "agent_015",
    name: "Tome",
    description:
      "An AI-powered storytelling format that automatically generates presentations with narrative flow and visual elements.",
    imageUrl: "https://tome.app/favicon.ico",
    category: "Presentation Creation",
    tags: ["presentations", "storytelling", "content design"],
    developer: "Tome, Inc.",
    capabilities: [
      "presentation generation",
      "story structuring",
      "image generation",
      "layout design",
    ],
    integrationPlatforms: ["Web"],
    apiEndpoint: "https://tome.app",
    supportedLanguages: ["English"],
    pricing: { monthly: 10, yearly: 96, freeTier: true },
    licenseType: "subscription",
    popularityScore: 4.4,
    reviewsCount: 1200,
    uptime: 99.8,
    releaseDate: "2021-08-15",
    lastUpdated: "2024-02-15",
    documentationURL: "https://help.tome.app",
    demoURL: "https://tome.app/demo",
  },
  {
    id: "agent_016",
    name: "Descript",
    description:
      "An AI-powered audio and video editor that enables text-based editing of media content with transcription and voice cloning capabilities.",
    imageUrl:
      "https://assets-global.website-files.com/5d761d627a6dfa1f4b3c1086/5d761d627a6dfa5a673c1098_favicon.png",
    category: "Media Editing",
    tags: ["audio editing", "video editing", "transcription"],
    developer: "Descript, Inc.",
    capabilities: [
      "audio transcription",
      "voice cloning",
      "video editing",
      "podcast production",
    ],
    integrationPlatforms: ["Windows", "macOS"],
    apiEndpoint: "https://www.descript.com",
    supportedLanguages: ["English"],
    pricing: { monthly: 15, yearly: 144, freeTier: true },
    licenseType: "subscription",
    popularityScore: 4.7,
    reviewsCount: 3500,
    uptime: 99.8,
    releaseDate: "2017-12-12",
    lastUpdated: "2024-02-28",
    documentationURL: "https://help.descript.com",
    demoURL: "https://www.descript.com/demo",
  },
];
