import type { Metadata } from "next";
import { Red_Hat_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer";

const redHatMono = Red_Hat_Mono({
  variable: "--font-red-hat-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatMono.variable} ${manrope.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen min-w-screen overflow-hidden">
          <div className="flex-grow">{children}</div>
          <Toaster richColors />
          <Footer />
        </div>
      </body>
    </html>
  );
}
